### ISSUE TITLE
Demo code?

### ISSUE THREAD

**Issue by LiJunnan1992** [aurooj/Hand-Segmentation-in-the-Wild#1]
It is a great work! I wonder if you can release a demo code to use your pre-trained models on a test image? I'm working on FPV action and would love to use the hand segmentation code and cite your paper. Thanks a lot!

**Comment by aurooj** [comment]
Sure, will upload the test code in a couple of days. Stay tuned!

**Comment by aurooj** [comment]
Hi LiJunnan, Test code is available now.

**Comment by LiJunnan1992** [comment]
Thanks!
