### ISSUE TITLE
EYTH Dataset masks saved as jpg in vid6

### ISSUE THREAD

**Issue by dani2112** [aurooj/Hand-Segmentation-in-the-Wild#4]
Hi,
The masks of vid6 in the EYTH dataset are provided as jpg which makes them unsusable.
Best regards
Daniel

**Comment by aurooj** [comment]
@dani2112 ..updated the dataset with masks in png format.

**Comment by dani2112** [comment]
Great thank you. Still some slight inconsistency as now the filenames in vid6 contain the extension .png while the ones in the other videos don't have any extension but that's something I can deal with myself :-)  Thanks for the dataset :+1:
