### ISSUE TITLE
Could not download the datasets

### ISSUE THREAD

**Issue by crazylyf** [aurooj/Hand-Segmentation-in-the-Wild#5]
Hi, thanks for your work! We tried to download the related datasets, but only EgoHands is downloadable. Are the links to datasets invalid now?

**Comment by aurooj** [comment]
@crazylyf Thanks for your interest! 
I have updated the links to EYTH, HOF, and EgoHands+ datasets now. 
Let me know if you still face any issues.

**Comment by aurooj** [comment]
For GTEA, you need to download it from their own website.
