### ISSUE TITLE
The URL list of original movies used in EgoYoutubeHand dataset

### ISSUE THREAD

**Issue by AtsushiHashimoto** [aurooj/Hand-Segmentation-in-the-Wild#7]
Hi! Nice and great work!
It helps me soooo much if you can make the list of URLs (or ids) of youtube videos you used in public. Is it possible?

**Comment by aurooj** [comment]
@AtsushiHashimoto Thanks for your interest. Let me check if I can find the urls somewhere in my data. 
I will get back to you in a day or two.

**Comment by AtsushiHashimoto** [comment]
Thanks for your effort! I believe information about the original video boosts your dataset's importance!

**Comment by aurooj** [comment]
@AtsushiHashimoto I have added the video links to the main project readme.md

**Comment by AtsushiHashimoto** [comment]
I saw the links! I thank you sooooo much!

**Comment by aurooj** [comment]
No problem! I hope it helps you! :)
