### ISSUE TITLE
Transparent Hands Dataset

### ISSUE THREAD

**Issue by test1230-lab** [aurooj/Hand-Segmentation-in-the-Wild#9]
How could I get the aligned and transparent pngs from the hands dataset? I don't have matlab.

**Comment by aurooj** [comment]
@test1230-lab Are you asking about EgoHands+ dataset? If yes, I can generate and share the link to the maps with you but there will be a delay of few days. 
 For EYTH and HOF, the links to the datasets are provided on the main project page.

**Comment by test1230-lab** [comment]
https://imgur.com/a/nvc3SQp something like this where the hands are cropped and a png

**Comment by test1230-lab** [comment]
Could a dataset like that be generated?
